package org.ontohub.idl;


/**
* org/ontohub/idl/_OntologyStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ontology.idl
* Montag, 29. Juli 2013 16:07 Uhr MESZ
*/

public class _OntologyStub extends org.omg.CORBA.portable.ObjectImpl implements org.ontohub.idl.Ontology
{

  public String getName (org.ontohub.idl.Iri iri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getName", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                String $result = org.ontohub.idl.TextHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getName (iri        );
            } finally {
                _releaseReply ($in);
            }
  } // getName

  public String getDescription (org.ontohub.idl.Iri iri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getDescription", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                String $result = org.ontohub.idl.TextHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getDescription (iri        );
            } finally {
                _releaseReply ($in);
            }
  } // getDescription

  public String[] getCategories (org.ontohub.idl.Iri iri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCategories", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                String $result[] = org.ontohub.idl.TextListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCategories (iri        );
            } finally {
                _releaseReply ($in);
            }
  } // getCategories

  public String[] getGroups (org.ontohub.idl.Iri iri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getGroups", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                String $result[] = org.ontohub.idl.TextListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getGroups (iri        );
            } finally {
                _releaseReply ($in);
            }
  } // getGroups

  public String[] getPrefixes (org.ontohub.idl.Iri iri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPrefixes", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                String $result[] = org.ontohub.idl.TextListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getPrefixes (iri        );
            } finally {
                _releaseReply ($in);
            }
  } // getPrefixes

  public void getSymbolList (org.ontohub.idl.Iri iri, org.ontohub.idl.SymbolListHolder symbolList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getSymbolList", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                symbolList.value = org.ontohub.idl.SymbolListHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getSymbolList (iri, symbolList        );
            } finally {
                _releaseReply ($in);
            }
  } // getSymbolList

  public void getSentenceList (org.ontohub.idl.Iri iri, org.ontohub.idl.SentenceListHolder sentenceList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getSentenceList", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                sentenceList.value = org.ontohub.idl.SentenceListHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getSentenceList (iri, sentenceList        );
            } finally {
                _releaseReply ($in);
            }
  } // getSentenceList

  public void getOntologyFractum (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyFractumHolder ontologyFractum)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getOntologyFractum", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                ontologyFractum.value = org.ontohub.idl.OntologyFractumHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getOntologyFractum (iri, ontologyFractum        );
            } finally {
                _releaseReply ($in);
            }
  } // getOntologyFractum

  public void getOntologyContent (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyContentHolder ontologyContent)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getOntologyContent", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                ontologyContent.value = org.ontohub.idl.OntologyContentHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getOntologyContent (iri, ontologyContent        );
            } finally {
                _releaseReply ($in);
            }
  } // getOntologyContent

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:org/ontohub/idl/Ontology:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _OntologyStub
