package org.ontohub.idl;


/**
* org/ontohub/idl/_RepositoryStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ontology.idl
* Montag, 29. Juli 2013 16:07 Uhr MESZ
*/

public class _RepositoryStub extends org.omg.CORBA.portable.ObjectImpl implements org.ontohub.idl.Repository
{

  public String getName (org.ontohub.idl.Iri iri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getName", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                String $result = org.ontohub.idl.TextHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getName (iri        );
            } finally {
                _releaseReply ($in);
            }
  } // getName

  public void getOntologyIriList (org.ontohub.idl.Iri iri, org.ontohub.idl.IriListHolder ontologyIriList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getOntologyIriList", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                ontologyIriList.value = org.ontohub.idl.IriListHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getOntologyIriList (iri, ontologyIriList        );
            } finally {
                _releaseReply ($in);
            }
  } // getOntologyIriList

  public void getOntologyFractumList (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyFractumListHolder ontologyFractumList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getOntologyFractumList", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                ontologyFractumList.value = org.ontohub.idl.OntologyFractumListHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getOntologyFractumList (iri, ontologyFractumList        );
            } finally {
                _releaseReply ($in);
            }
  } // getOntologyFractumList

  public void getOntologyContentList (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyContentListHolder ontologyContentList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getOntologyContentList", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                ontologyContentList.value = org.ontohub.idl.OntologyContentListHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getOntologyContentList (iri, ontologyContentList        );
            } finally {
                _releaseReply ($in);
            }
  } // getOntologyContentList

  public void addOntology (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri ontologyIri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addOntology", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.IriHelper.write ($out, ontologyIri);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addOntology (iri, ontologyIri        );
            } finally {
                _releaseReply ($in);
            }
  } // addOntology

  public void delOntology (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri ontologyIri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("delOntology", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.IriHelper.write ($out, ontologyIri);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                delOntology (iri, ontologyIri        );
            } finally {
                _releaseReply ($in);
            }
  } // delOntology

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:org/ontohub/idl/Repository:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _RepositoryStub
