package org.ontohub.idl;


/**
* org/ontohub/idl/OntologyContent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ontology.idl
* Montag, 29. Juli 2013 16:07 Uhr MESZ
*/

public final class OntologyContent implements org.omg.CORBA.portable.IDLEntity
{
  public org.ontohub.idl.OntologyFractum meta = null;
  public org.ontohub.idl.Symbol symbolList[] = null;
  public org.ontohub.idl.Sentence sentenceList[] = null;

  public OntologyContent ()
  {
  } // ctor

  public OntologyContent (org.ontohub.idl.OntologyFractum _meta, org.ontohub.idl.Symbol[] _symbolList, org.ontohub.idl.Sentence[] _sentenceList)
  {
    meta = _meta;
    symbolList = _symbolList;
    sentenceList = _sentenceList;
  } // ctor

} // class OntologyContent
