package org.ontohub.idl;

/**
* org/ontohub/idl/OntologyFractumHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ontology.idl
* Montag, 29. Juli 2013 16:07 Uhr MESZ
*/

public final class OntologyFractumHolder implements org.omg.CORBA.portable.Streamable
{
  public org.ontohub.idl.OntologyFractum value = null;

  public OntologyFractumHolder ()
  {
  }

  public OntologyFractumHolder (org.ontohub.idl.OntologyFractum initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.ontohub.idl.OntologyFractumHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.ontohub.idl.OntologyFractumHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.ontohub.idl.OntologyFractumHelper.type ();
  }

}
