package org.ontohub.idl;


/**
* org/ontohub/idl/OntologyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ontology.idl
* Montag, 29. Juli 2013 16:07 Uhr MESZ
*/

public interface OntologyOperations 
{
  String getName (org.ontohub.idl.Iri iri);
  String getDescription (org.ontohub.idl.Iri iri);
  String[] getCategories (org.ontohub.idl.Iri iri);
  String[] getGroups (org.ontohub.idl.Iri iri);
  String[] getPrefixes (org.ontohub.idl.Iri iri);
  void getSymbolList (org.ontohub.idl.Iri iri, org.ontohub.idl.SymbolListHolder symbolList);
  void getSentenceList (org.ontohub.idl.Iri iri, org.ontohub.idl.SentenceListHolder sentenceList);
  void getOntologyFractum (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyFractumHolder ontologyFractum);
  void getOntologyContent (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyContentHolder ontologyContent);
} // interface OntologyOperations
