package org.ontohub.idl;

/**
* org/ontohub/idl/RepositoryFractumHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ontology.idl
* Montag, 29. Juli 2013 16:07 Uhr MESZ
*/

public final class RepositoryFractumHolder implements org.omg.CORBA.portable.Streamable
{
  public org.ontohub.idl.RepositoryFractum value = null;

  public RepositoryFractumHolder ()
  {
  }

  public RepositoryFractumHolder (org.ontohub.idl.RepositoryFractum initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.ontohub.idl.RepositoryFractumHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.ontohub.idl.RepositoryFractumHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.ontohub.idl.RepositoryFractumHelper.type ();
  }

}
