package org.ontohub.idl;


/**
* org/ontohub/idl/RepositoryContent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ontology.idl
* Montag, 29. Juli 2013 16:07 Uhr MESZ
*/

public final class RepositoryContent implements org.omg.CORBA.portable.IDLEntity
{
  public org.ontohub.idl.Iri iri = null;
  public String name = null;
  public org.ontohub.idl.OntologyContent ontologyContentList[] = null;

  public RepositoryContent ()
  {
  } // ctor

  public RepositoryContent (org.ontohub.idl.Iri _iri, String _name, org.ontohub.idl.OntologyContent[] _ontologyContentList)
  {
    iri = _iri;
    name = _name;
    ontologyContentList = _ontologyContentList;
  } // ctor

} // class RepositoryContent
