package org.ontohub.idl;


/**
* org/ontohub/idl/RepositoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ontology.idl
* Montag, 29. Juli 2013 16:07 Uhr MESZ
*/

public interface RepositoryOperations 
{
  String getName (org.ontohub.idl.Iri iri);
  void getOntologyIriList (org.ontohub.idl.Iri iri, org.ontohub.idl.IriListHolder ontologyIriList);
  void getOntologyFractumList (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyFractumListHolder ontologyFractumList);
  void getOntologyContentList (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyContentListHolder ontologyContentList);
  void addOntology (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri ontologyIri);
  void delOntology (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri ontologyIri);
} // interface RepositoryOperations
