package org.ontohub.idl;


/**
* org/ontohub/idl/RepositoryFractum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ontology.idl
* Montag, 29. Juli 2013 16:07 Uhr MESZ
*/

public final class RepositoryFractum implements org.omg.CORBA.portable.IDLEntity
{
  public org.ontohub.idl.Iri iri = null;
  public String name = null;
  public org.ontohub.idl.OntologyFractum ontologyFractumList[] = null;

  public RepositoryFractum ()
  {
  } // ctor

  public RepositoryFractum (org.ontohub.idl.Iri _iri, String _name, org.ontohub.idl.OntologyFractum[] _ontologyFractumList)
  {
    iri = _iri;
    name = _name;
    ontologyFractumList = _ontologyFractumList;
  } // ctor

} // class RepositoryFractum
