package org.ontohub.idl;

/**
* org/ontohub/idl/RepositoryContentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ontology.idl
* Montag, 29. Juli 2013 16:07 Uhr MESZ
*/

public final class RepositoryContentHolder implements org.omg.CORBA.portable.Streamable
{
  public org.ontohub.idl.RepositoryContent value = null;

  public RepositoryContentHolder ()
  {
  }

  public RepositoryContentHolder (org.ontohub.idl.RepositoryContent initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.ontohub.idl.RepositoryContentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.ontohub.idl.RepositoryContentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.ontohub.idl.RepositoryContentHelper.type ();
  }

}
