package org.ontohub.idl;


/**
* org/ontohub/idl/SentenceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ontology.idl
* Montag, 29. Juli 2013 16:07 Uhr MESZ
*/

abstract public class SentenceHelper
{
  private static String  _id = "IDL:org/ontohub/idl/Sentence:1.0";

  public static void insert (org.omg.CORBA.Any a, org.ontohub.idl.Sentence that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.ontohub.idl.Sentence extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.ontohub.idl.IriHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "iri",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.ontohub.idl.TextHelper.id (), "Text", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "form",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.ontohub.idl.SentenceHelper.id (), "Sentence", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.ontohub.idl.Sentence read (org.omg.CORBA.portable.InputStream istream)
  {
    org.ontohub.idl.Sentence value = new org.ontohub.idl.Sentence ();
    value.iri = org.ontohub.idl.IriHelper.read (istream);
    value.form = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.ontohub.idl.Sentence value)
  {
    org.ontohub.idl.IriHelper.write (ostream, value.iri);
    ostream.write_string (value.form);
  }

}
