package org.ontohub.idl;


/**
* org/ontohub/idl/Symbol.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ontology.idl
* Montag, 29. Juli 2013 16:07 Uhr MESZ
*/

public final class Symbol implements org.omg.CORBA.portable.IDLEntity
{
  public org.ontohub.idl.Iri iri = null;

  public Symbol ()
  {
  } // ctor

  public Symbol (org.ontohub.idl.Iri _iri)
  {
    iri = _iri;
  } // ctor

} // class Symbol
