package org.ontohub.idl;

/**
* org/ontohub/idl/SymbolHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ontology.idl
* Montag, 29. Juli 2013 16:07 Uhr MESZ
*/

public final class SymbolHolder implements org.omg.CORBA.portable.Streamable
{
  public org.ontohub.idl.Symbol value = null;

  public SymbolHolder ()
  {
  }

  public SymbolHolder (org.ontohub.idl.Symbol initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.ontohub.idl.SymbolHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.ontohub.idl.SymbolHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.ontohub.idl.SymbolHelper.type ();
  }

}
