package org.ontohub.idl;


/**
* org/ontohub/idl/_OntologyStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

public class _OntologyStub extends org.omg.CORBA.portable.ObjectImpl implements org.ontohub.idl.Ontology
{

  public String getName (org.ontohub.idl.Iri iri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getName", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                String $result = org.ontohub.idl.TextHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getName (iri        );
            } finally {
                _releaseReply ($in);
            }
  } // getName

  public String getDescription (org.ontohub.idl.Iri iri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getDescription", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                String $result = org.ontohub.idl.TextHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getDescription (iri        );
            } finally {
                _releaseReply ($in);
            }
  } // getDescription

  public String[] getCategories (org.ontohub.idl.Iri iri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCategories", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                String $result[] = org.ontohub.idl.TextListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCategories (iri        );
            } finally {
                _releaseReply ($in);
            }
  } // getCategories

  public String[] getGroups (org.ontohub.idl.Iri iri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getGroups", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                String $result[] = org.ontohub.idl.TextListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getGroups (iri        );
            } finally {
                _releaseReply ($in);
            }
  } // getGroups

  public String[] getPrefixes (org.ontohub.idl.Iri iri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getPrefixes", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                String $result[] = org.ontohub.idl.TextListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getPrefixes (iri        );
            } finally {
                _releaseReply ($in);
            }
  } // getPrefixes

  public org.ontohub.idl.Iri getCurrentVersionIri (org.ontohub.idl.Iri iri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getCurrentVersionIri", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                org.ontohub.idl.Iri $result = org.ontohub.idl.IriHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getCurrentVersionIri (iri        );
            } finally {
                _releaseReply ($in);
            }
  } // getCurrentVersionIri

  public void setName (org.ontohub.idl.Iri iri, String name)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setName", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.TextHelper.write ($out, name);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setName (iri, name        );
            } finally {
                _releaseReply ($in);
            }
  } // setName

  public void setDescription (org.ontohub.idl.Iri iri, String description)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setDescription", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.TextHelper.write ($out, description);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setDescription (iri, description        );
            } finally {
                _releaseReply ($in);
            }
  } // setDescription

  public void setCategories (org.ontohub.idl.Iri iri, String[] categories)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setCategories", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.TextListHelper.write ($out, categories);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setCategories (iri, categories        );
            } finally {
                _releaseReply ($in);
            }
  } // setCategories

  public void addCateogry (org.ontohub.idl.Iri iri, String category)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addCateogry", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.TextHelper.write ($out, category);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addCateogry (iri, category        );
            } finally {
                _releaseReply ($in);
            }
  } // addCateogry

  public void delCategory (org.ontohub.idl.Iri iri, String category)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("delCategory", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.TextHelper.write ($out, category);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                delCategory (iri, category        );
            } finally {
                _releaseReply ($in);
            }
  } // delCategory

  public void setGroups (org.ontohub.idl.Iri iri, String[] groups)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setGroups", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.TextListHelper.write ($out, groups);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setGroups (iri, groups        );
            } finally {
                _releaseReply ($in);
            }
  } // setGroups

  public void addGroup (org.ontohub.idl.Iri iri, String group)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addGroup", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.TextHelper.write ($out, group);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addGroup (iri, group        );
            } finally {
                _releaseReply ($in);
            }
  } // addGroup

  public void delGroup (org.ontohub.idl.Iri iri, String group)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("delGroup", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.TextHelper.write ($out, group);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                delGroup (iri, group        );
            } finally {
                _releaseReply ($in);
            }
  } // delGroup

  public void setPrefixes (org.ontohub.idl.Iri iri, String[] prefixes)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setPrefixes", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.TextListHelper.write ($out, prefixes);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setPrefixes (iri, prefixes        );
            } finally {
                _releaseReply ($in);
            }
  } // setPrefixes

  public void addPrefix (org.ontohub.idl.Iri iri, String prefix)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addPrefix", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.TextHelper.write ($out, prefix);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addPrefix (iri, prefix        );
            } finally {
                _releaseReply ($in);
            }
  } // addPrefix

  public void delPrefix (org.ontohub.idl.Iri iri, String prefix)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("delPrefix", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.TextHelper.write ($out, prefix);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                delPrefix (iri, prefix        );
            } finally {
                _releaseReply ($in);
            }
  } // delPrefix

  public void setCurrentVersionIri (org.ontohub.idl.Iri iri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setCurrentVersionIri", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setCurrentVersionIri (iri        );
            } finally {
                _releaseReply ($in);
            }
  } // setCurrentVersionIri

  public void getFractum (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyFractumHolder fractum)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getFractum", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                fractum.value = org.ontohub.idl.OntologyFractumHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getFractum (iri, fractum        );
            } finally {
                _releaseReply ($in);
            }
  } // getFractum

  public void getContent (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyContentHolder content)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getContent", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                content.value = org.ontohub.idl.OntologyContentHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getContent (iri, content        );
            } finally {
                _releaseReply ($in);
            }
  } // getContent

  public void setFractum (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyFractum fractum)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setFractum", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.OntologyFractumHelper.write ($out, fractum);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setFractum (iri, fractum        );
            } finally {
                _releaseReply ($in);
            }
  } // setFractum

  public void setContent (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyContent content)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setContent", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.OntologyContentHelper.write ($out, content);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setContent (iri, content        );
            } finally {
                _releaseReply ($in);
            }
  } // setContent

  public void getVersionIriList (org.ontohub.idl.Iri iri, org.ontohub.idl.IriHolder versionIriList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getVersionIriList", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                versionIriList.value = org.ontohub.idl.IriHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getVersionIriList (iri, versionIriList        );
            } finally {
                _releaseReply ($in);
            }
  } // getVersionIriList

  public void setVersionIriList (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri versionIriList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setVersionIriList", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.IriHelper.write ($out, versionIriList);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setVersionIriList (iri, versionIriList        );
            } finally {
                _releaseReply ($in);
            }
  } // setVersionIriList

  public void addVersionIri (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri versionIri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addVersionIri", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.IriHelper.write ($out, versionIri);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addVersionIri (iri, versionIri        );
            } finally {
                _releaseReply ($in);
            }
  } // addVersionIri

  public void delVersionIri (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri versionIri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("delVersionIri", true);
                org.ontohub.idl.IriHelper.write ($out, iri);
                org.ontohub.idl.IriHelper.write ($out, versionIri);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                delVersionIri (iri, versionIri        );
            } finally {
                _releaseReply ($in);
            }
  } // delVersionIri

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:org/ontohub/idl/Ontology:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _OntologyStub
