package org.ontohub.idl;


/**
* org/ontohub/idl/Iri.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

public final class Iri implements org.omg.CORBA.portable.IDLEntity
{
  public String iriText = null;

  public Iri ()
  {
  } // ctor

  public Iri (String _iriText)
  {
    iriText = _iriText;
  } // ctor

} // class Iri
