package org.ontohub.idl;


/**
* org/ontohub/idl/Language.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

public final class Language implements org.omg.CORBA.portable.IDLEntity
{
  public org.ontohub.idl.Iri iri = null;
  public String name = null;

  public Language ()
  {
  } // ctor

  public Language (org.ontohub.idl.Iri _iri, String _name)
  {
    iri = _iri;
    name = _name;
  } // ctor

} // class Language
