package org.ontohub.idl;

/**
* org/ontohub/idl/LogicHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

public final class LogicHolder implements org.omg.CORBA.portable.Streamable
{
  public org.ontohub.idl.Logic value = null;

  public LogicHolder ()
  {
  }

  public LogicHolder (org.ontohub.idl.Logic initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.ontohub.idl.LogicHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.ontohub.idl.LogicHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.ontohub.idl.LogicHelper.type ();
  }

}
