package org.ontohub.idl;


/**
* org/ontohub/idl/Metadatum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

public final class Metadatum implements org.omg.CORBA.portable.IDLEntity
{
  public org.ontohub.idl.Iri iri = null;
  public org.ontohub.idl.Iri kindIri = null;
  public org.ontohub.idl.Iri kindName = null;
  public org.ontohub.idl.Iri entryIri = null;
  public String value = null;

  public Metadatum ()
  {
  } // ctor

  public Metadatum (org.ontohub.idl.Iri _iri, org.ontohub.idl.Iri _kindIri, org.ontohub.idl.Iri _kindName, org.ontohub.idl.Iri _entryIri, String _value)
  {
    iri = _iri;
    kindIri = _kindIri;
    kindName = _kindName;
    entryIri = _entryIri;
    value = _value;
  } // ctor

} // class Metadatum
