package org.ontohub.idl;

/**
* org/ontohub/idl/MetricsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

public final class MetricsHolder implements org.omg.CORBA.portable.Streamable
{
  public org.ontohub.idl.Metrics value = null;

  public MetricsHolder ()
  {
  }

  public MetricsHolder (org.ontohub.idl.Metrics initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.ontohub.idl.MetricsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.ontohub.idl.MetricsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.ontohub.idl.MetricsHelper.type ();
  }

}
