package org.ontohub.idl;


/**
* org/ontohub/idl/OntologyBaseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

public interface OntologyBaseOperations 
{
  void selectOntologyIriList (String name, String category, String group, org.ontohub.idl.Iri languageIri, org.ontohub.idl.Iri projectIri, org.ontohub.idl.IriListHolder iriList);
  void selectOntologyIriListByName (String name, org.ontohub.idl.IriListHolder iriList);
  void selectOntologyIriListByCategory (String category, org.ontohub.idl.IriListHolder iriList);
  void selectOntologyIriListByGroup (String group, org.ontohub.idl.IriListHolder iriList);
  void selectOntologyIriListByLanguageIri (org.ontohub.idl.Iri languageIri, org.ontohub.idl.IriListHolder iriList);
  void selectOntologyIriListByProjectIri (org.ontohub.idl.Iri projectIri, org.ontohub.idl.IriListHolder iriList);
  void getOntologyIriList ();
  void selectOntologyFractumList (String name, String category, String group, org.ontohub.idl.Iri languageIri, org.ontohub.idl.Iri projectIri, org.ontohub.idl.OntologyFractumListHolder fractumList);
  void selectOntologyFractumListByName (String name, org.ontohub.idl.OntologyFractumListHolder fractumList);
  void selectOntologyFractumListByCategory (String category, org.ontohub.idl.OntologyFractumListHolder fractumList);
  void selectOntologyFractumListByGroup (String group, org.ontohub.idl.OntologyFractumListHolder fractumList);
  void selectOntologyFracutmListByLanguageIri (org.ontohub.idl.Iri languageIri, org.ontohub.idl.OntologyFractumListHolder fractumList);
  void selectOntologyFractumListByProjectIri (org.ontohub.idl.Iri projectIri, org.ontohub.idl.OntologyFractumListHolder fractumList);
  void getOntologyFractumList ();
  void selectOntologyContentList (String name, String category, String group, org.ontohub.idl.Iri languageIri, org.ontohub.idl.Iri projectIri, org.ontohub.idl.OntologyContentListHolder contentList);
  void selectOntologyContentListByName (String name, org.ontohub.idl.OntologyContentListHolder contentList);
  void selectOntologyContentListByCategory (String category, org.ontohub.idl.OntologyContentListHolder contentList);
  void selectOntologyContentListByGroup (String group, org.ontohub.idl.OntologyContentListHolder contentList);
  void selectOntologyContentListByLanguageIri (org.ontohub.idl.Iri languageIri, org.ontohub.idl.OntologyContentListHolder contentList);
  void selectOntologyContentListByProjectIri (org.ontohub.idl.Iri projectIri, org.ontohub.idl.OntologyContentListHolder contentList);
  void getOntologyContentList ();
  void insertOntology (org.ontohub.idl.OntologyContent ontologyContent, org.ontohub.idl.IriHolder iri);
  void updateOntology (org.ontohub.idl.OntologyContent ontologyContent);
  void removeOntology (org.ontohub.idl.Iri iri);
} // interface OntologyBaseOperations
