package org.ontohub.idl;

/**
* org/ontohub/idl/OntologyVersionContentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

public final class OntologyVersionContentHolder implements org.omg.CORBA.portable.Streamable
{
  public org.ontohub.idl.OntologyVersionContent value = null;

  public OntologyVersionContentHolder ()
  {
  }

  public OntologyVersionContentHolder (org.ontohub.idl.OntologyVersionContent initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.ontohub.idl.OntologyVersionContentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.ontohub.idl.OntologyVersionContentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.ontohub.idl.OntologyVersionContentHelper.type ();
  }

}
