package org.ontohub.idl;


/**
* org/ontohub/idl/OntologyContentHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

abstract public class OntologyContentHelper
{
  private static String  _id = "IDL:org/ontohub/idl/OntologyContent:1.0";

  public static void insert (org.omg.CORBA.Any a, org.ontohub.idl.OntologyContent that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.ontohub.idl.OntologyContent extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.ontohub.idl.OntologyFractumHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "fractum",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.ontohub.idl.OntologyVersionContentHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "currentVersion",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.ontohub.idl.OntologyContentHelper.id (), "OntologyContent", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.ontohub.idl.OntologyContent read (org.omg.CORBA.portable.InputStream istream)
  {
    org.ontohub.idl.OntologyContent value = new org.ontohub.idl.OntologyContent ();
    value.fractum = org.ontohub.idl.OntologyFractumHelper.read (istream);
    value.currentVersion = org.ontohub.idl.OntologyVersionContentHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.ontohub.idl.OntologyContent value)
  {
    org.ontohub.idl.OntologyFractumHelper.write (ostream, value.fractum);
    org.ontohub.idl.OntologyVersionContentHelper.write (ostream, value.currentVersion);
  }

}
