package org.ontohub.idl;


/**
* org/ontohub/idl/OntologyVersionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

public interface OntologyVersionOperations 
{
  void getBlob (org.ontohub.idl.Iri iri);
  void getSymbolList (org.ontohub.idl.Iri iri, org.ontohub.idl.SymbolListHolder symbolList);
  void getSentenceList (org.ontohub.idl.Iri iri, org.ontohub.idl.SentenceListHolder sentenceList);
  void getMetricsList (org.ontohub.idl.Iri iri, org.ontohub.idl.MetricsListHolder metricsList);
  void getNoteList (org.ontohub.idl.Iri iri, org.ontohub.idl.NoteListHolder noteList);
  void getMetadatumList (org.ontohub.idl.Iri iri, org.ontohub.idl.MetadatumListHolder metadatumList);
  void setSymbolList (org.ontohub.idl.Iri iri, org.ontohub.idl.Symbol[] symbolList);
  void addSymbol (org.ontohub.idl.Iri iri, org.ontohub.idl.Symbol symbol);
  void delSymbol (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri symbolIri);
  void setSentenceList (org.ontohub.idl.Iri iri, org.ontohub.idl.Sentence[] sentenceList);
  void addSentence (org.ontohub.idl.Iri iri, org.ontohub.idl.Sentence sentence);
  void delSentence (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri sentenceIri);
  void setMetricsList (org.ontohub.idl.Iri iri, org.ontohub.idl.Metrics[] metricsList);
  void addMetrics (org.ontohub.idl.Iri iri, org.ontohub.idl.Metrics metrics);
  void delMetrics (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri metricsIri);
  void setNoteList (org.ontohub.idl.Iri iri, org.ontohub.idl.Note[] noteList);
  void addNote (org.ontohub.idl.Iri iri, org.ontohub.idl.Note note);
  void delNote (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri noteIri);
  void setMetadatumList (org.ontohub.idl.Iri iri, org.ontohub.idl.Metadatum[] metadatumList);
  void addMetadatum (org.ontohub.idl.Iri iri, org.ontohub.idl.Metadatum metadatum);
  void delMetadatum (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri metadatumIri);
  void getContent (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyVersionContentHolder content);
  void setContent (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyVersionContent content);
} // interface OntologyVersionOperations
