package org.ontohub.idl;


/**
* org/ontohub/idl/OntologyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

public interface OntologyOperations 
{
  String getName (org.ontohub.idl.Iri iri);
  String getDescription (org.ontohub.idl.Iri iri);
  String[] getCategories (org.ontohub.idl.Iri iri);
  String[] getGroups (org.ontohub.idl.Iri iri);
  String[] getPrefixes (org.ontohub.idl.Iri iri);
  org.ontohub.idl.Iri getCurrentVersionIri (org.ontohub.idl.Iri iri);
  void setName (org.ontohub.idl.Iri iri, String name);
  void setDescription (org.ontohub.idl.Iri iri, String description);
  void setCategories (org.ontohub.idl.Iri iri, String[] categories);
  void addCateogry (org.ontohub.idl.Iri iri, String category);
  void delCategory (org.ontohub.idl.Iri iri, String category);
  void setGroups (org.ontohub.idl.Iri iri, String[] groups);
  void addGroup (org.ontohub.idl.Iri iri, String group);
  void delGroup (org.ontohub.idl.Iri iri, String group);
  void setPrefixes (org.ontohub.idl.Iri iri, String[] prefixes);
  void addPrefix (org.ontohub.idl.Iri iri, String prefix);
  void delPrefix (org.ontohub.idl.Iri iri, String prefix);
  void setCurrentVersionIri (org.ontohub.idl.Iri iri);
  void getFractum (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyFractumHolder fractum);
  void getContent (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyContentHolder content);
  void setFractum (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyFractum fractum);
  void setContent (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyContent content);
  void getVersionIriList (org.ontohub.idl.Iri iri, org.ontohub.idl.IriHolder versionIriList);
  void setVersionIriList (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri versionIriList);
  void addVersionIri (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri versionIri);
  void delVersionIri (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri versionIri);
} // interface OntologyOperations
