package org.ontohub.idl;


/**
* org/ontohub/idl/OntologyVersionContentHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

abstract public class OntologyVersionContentHelper
{
  private static String  _id = "IDL:org/ontohub/idl/OntologyVersionContent:1.0";

  public static void insert (org.omg.CORBA.Any a, org.ontohub.idl.OntologyVersionContent that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.ontohub.idl.OntologyVersionContent extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [7];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.ontohub.idl.IriHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "iri",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_char);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.ontohub.idl.BlobHelper.id (), "Blob", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "blob",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.ontohub.idl.SymbolHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.ontohub.idl.SymbolListHelper.id (), "SymbolList", _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "symbolList",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.ontohub.idl.SentenceHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.ontohub.idl.SentenceListHelper.id (), "SentenceList", _tcOf_members0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "sentenceList",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.ontohub.idl.MetricsHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.ontohub.idl.MetricsListHelper.id (), "MetricsList", _tcOf_members0);
          _members0[4] = new org.omg.CORBA.StructMember (
            "metricsList",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.ontohub.idl.NoteHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.ontohub.idl.NoteListHelper.id (), "NoteList", _tcOf_members0);
          _members0[5] = new org.omg.CORBA.StructMember (
            "noteList",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.ontohub.idl.MetadatumHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.ontohub.idl.MetadatumListHelper.id (), "MetadatumList", _tcOf_members0);
          _members0[6] = new org.omg.CORBA.StructMember (
            "metadatumList",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.ontohub.idl.OntologyVersionContentHelper.id (), "OntologyVersionContent", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.ontohub.idl.OntologyVersionContent read (org.omg.CORBA.portable.InputStream istream)
  {
    org.ontohub.idl.OntologyVersionContent value = new org.ontohub.idl.OntologyVersionContent ();
    value.iri = org.ontohub.idl.IriHelper.read (istream);
    value.blob = org.ontohub.idl.BlobHelper.read (istream);
    value.symbolList = org.ontohub.idl.SymbolListHelper.read (istream);
    value.sentenceList = org.ontohub.idl.SentenceListHelper.read (istream);
    value.metricsList = org.ontohub.idl.MetricsListHelper.read (istream);
    value.noteList = org.ontohub.idl.NoteListHelper.read (istream);
    value.metadatumList = org.ontohub.idl.MetadatumListHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.ontohub.idl.OntologyVersionContent value)
  {
    org.ontohub.idl.IriHelper.write (ostream, value.iri);
    org.ontohub.idl.BlobHelper.write (ostream, value.blob);
    org.ontohub.idl.SymbolListHelper.write (ostream, value.symbolList);
    org.ontohub.idl.SentenceListHelper.write (ostream, value.sentenceList);
    org.ontohub.idl.MetricsListHelper.write (ostream, value.metricsList);
    org.ontohub.idl.NoteListHelper.write (ostream, value.noteList);
    org.ontohub.idl.MetadatumListHelper.write (ostream, value.metadatumList);
  }

}
