package org.ontohub.idl;


/**
* org/ontohub/idl/OntologyVersionContent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

public final class OntologyVersionContent implements org.omg.CORBA.portable.IDLEntity
{
  public org.ontohub.idl.Iri iri = null;
  public char blob[] = null;
  public org.ontohub.idl.Symbol symbolList[] = null;
  public org.ontohub.idl.Sentence sentenceList[] = null;
  public org.ontohub.idl.Metrics metricsList[] = null;
  public org.ontohub.idl.Note noteList[] = null;
  public org.ontohub.idl.Metadatum metadatumList[] = null;

  public OntologyVersionContent ()
  {
  } // ctor

  public OntologyVersionContent (org.ontohub.idl.Iri _iri, char[] _blob, org.ontohub.idl.Symbol[] _symbolList, org.ontohub.idl.Sentence[] _sentenceList, org.ontohub.idl.Metrics[] _metricsList, org.ontohub.idl.Note[] _noteList, org.ontohub.idl.Metadatum[] _metadatumList)
  {
    iri = _iri;
    blob = _blob;
    symbolList = _symbolList;
    sentenceList = _sentenceList;
    metricsList = _metricsList;
    noteList = _noteList;
    metadatumList = _metadatumList;
  } // ctor

} // class OntologyVersionContent
