package org.ontohub.idl;


/**
* org/ontohub/idl/OntologyFractum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

public final class OntologyFractum implements org.omg.CORBA.portable.IDLEntity
{
  public org.ontohub.idl.Iri iri = null;
  public String name = null;
  public String description = null;
  public String categories[] = null;
  public String groups[] = null;
  public String prefixes[] = null;
  public org.ontohub.idl.Iri languageIri = null;
  public org.ontohub.idl.Iri projectIri = null;
  public org.ontohub.idl.Iri currentVersionIri = null;

  public OntologyFractum ()
  {
  } // ctor

  public OntologyFractum (org.ontohub.idl.Iri _iri, String _name, String _description, String[] _categories, String[] _groups, String[] _prefixes, org.ontohub.idl.Iri _languageIri, org.ontohub.idl.Iri _projectIri, org.ontohub.idl.Iri _currentVersionIri)
  {
    iri = _iri;
    name = _name;
    description = _description;
    categories = _categories;
    groups = _groups;
    prefixes = _prefixes;
    languageIri = _languageIri;
    projectIri = _projectIri;
    currentVersionIri = _currentVersionIri;
  } // ctor

} // class OntologyFractum
