package org.ontohub.idl;


/**
* org/ontohub/idl/OntologyBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

public interface OntologyBase extends OntologyBaseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface OntologyBase
