package org.ontohub.idl;


/**
* org/ontohub/idl/OntologyContentListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

public final class OntologyContentListHolder implements org.omg.CORBA.portable.Streamable
{
  public org.ontohub.idl.OntologyContent value[] = null;

  public OntologyContentListHolder ()
  {
  }

  public OntologyContentListHolder (org.ontohub.idl.OntologyContent[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.ontohub.idl.OntologyContentListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.ontohub.idl.OntologyContentListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.ontohub.idl.OntologyContentListHelper.type ();
  }

}
