package org.ontohub.idl;


/**
* org/ontohub/idl/RepositoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

public interface RepositoryOperations 
{
  String getName (org.ontohub.idl.Iri iri);
  void setName (org.ontohub.idl.Iri iri, String name);
  void getOntologyIriList (org.ontohub.idl.Iri iri, org.ontohub.idl.IriListHolder ontologyIriList);
  void getOntologyFractumList (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyFractumListHolder ontologyFractumList);
  void getOntologyContentList (org.ontohub.idl.Iri iri, org.ontohub.idl.OntologyContentListHolder ontologyContentList);
  void getRepositoryFractum (org.ontohub.idl.Iri iri, org.ontohub.idl.RepositoryFractumHolder repositoryFractum);
  void getRepositoryContent (org.ontohub.idl.Iri iri, org.ontohub.idl.RepositoryContentHolder repositoryContent);
  void setOntologyIriList (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri[] ontologyIriList);
  void addOntology (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri ontologyIri);
  void delOntology (org.ontohub.idl.Iri iri, org.ontohub.idl.Iri ontologyIri);
  void setRepositoryFractum (org.ontohub.idl.Iri iri, org.ontohub.idl.RepositoryFractum repositoryFractum);
  void setRepositoryContent (org.ontohub.idl.Iri iri, org.ontohub.idl.RepositoryContent repositoryContent);
} // interface RepositoryOperations
