package org.ontohub.idl;


/**
* org/ontohub/idl/RepositoryContentListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:12 Uhr MESZ
*/

public final class RepositoryContentListHolder implements org.omg.CORBA.portable.Streamable
{
  public org.ontohub.idl.RepositoryContent value[] = null;

  public RepositoryContentListHolder ()
  {
  }

  public RepositoryContentListHolder (org.ontohub.idl.RepositoryContent[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.ontohub.idl.RepositoryContentListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.ontohub.idl.RepositoryContentListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.ontohub.idl.RepositoryContentListHelper.type ();
  }

}
