package org.oor.persistence;


/**
* org/oor/persistence/_OntologyVersionStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public class _OntologyVersionStub extends org.omg.CORBA.portable.ObjectImpl implements org.oor.persistence.OntologyVersion
{

  public void getBlob (org.oor.persistence.Iri iri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getBlob", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getBlob (iri        );
            } finally {
                _releaseReply ($in);
            }
  } // getBlob

  public void getSymbolList (org.oor.persistence.Iri iri, org.oor.persistence.SymbolListHolder symbolList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getSymbolList", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                symbolList.value = org.oor.persistence.SymbolListHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getSymbolList (iri, symbolList        );
            } finally {
                _releaseReply ($in);
            }
  } // getSymbolList

  public void getSentenceList (org.oor.persistence.Iri iri, org.oor.persistence.SentenceListHolder sentenceList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getSentenceList", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                sentenceList.value = org.oor.persistence.SentenceListHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getSentenceList (iri, sentenceList        );
            } finally {
                _releaseReply ($in);
            }
  } // getSentenceList

  public void getMetricsList (org.oor.persistence.Iri iri, org.oor.persistence.MetricsListHolder metricsList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMetricsList", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                metricsList.value = org.oor.persistence.MetricsListHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getMetricsList (iri, metricsList        );
            } finally {
                _releaseReply ($in);
            }
  } // getMetricsList

  public void getNoteList (org.oor.persistence.Iri iri, org.oor.persistence.NoteListHolder noteList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getNoteList", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                noteList.value = org.oor.persistence.NoteListHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getNoteList (iri, noteList        );
            } finally {
                _releaseReply ($in);
            }
  } // getNoteList

  public void getMetadatumList (org.oor.persistence.Iri iri, org.oor.persistence.MetadatumListHolder metadatumList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getMetadatumList", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                metadatumList.value = org.oor.persistence.MetadatumListHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getMetadatumList (iri, metadatumList        );
            } finally {
                _releaseReply ($in);
            }
  } // getMetadatumList

  public void setSymbolList (org.oor.persistence.Iri iri, org.oor.persistence.Symbol[] symbolList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setSymbolList", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                org.oor.persistence.SymbolListHelper.write ($out, symbolList);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setSymbolList (iri, symbolList        );
            } finally {
                _releaseReply ($in);
            }
  } // setSymbolList

  public void addSymbol (org.oor.persistence.Iri iri, org.oor.persistence.Symbol symbol)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addSymbol", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                org.oor.persistence.SymbolHelper.write ($out, symbol);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addSymbol (iri, symbol        );
            } finally {
                _releaseReply ($in);
            }
  } // addSymbol

  public void delSymbol (org.oor.persistence.Iri iri, org.oor.persistence.Iri symbolIri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("delSymbol", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                org.oor.persistence.IriHelper.write ($out, symbolIri);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                delSymbol (iri, symbolIri        );
            } finally {
                _releaseReply ($in);
            }
  } // delSymbol

  public void setSentenceList (org.oor.persistence.Iri iri, org.oor.persistence.Sentence[] sentenceList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setSentenceList", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                org.oor.persistence.SentenceListHelper.write ($out, sentenceList);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setSentenceList (iri, sentenceList        );
            } finally {
                _releaseReply ($in);
            }
  } // setSentenceList

  public void addSentence (org.oor.persistence.Iri iri, org.oor.persistence.Sentence sentence)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addSentence", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                org.oor.persistence.SentenceHelper.write ($out, sentence);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addSentence (iri, sentence        );
            } finally {
                _releaseReply ($in);
            }
  } // addSentence

  public void delSentence (org.oor.persistence.Iri iri, org.oor.persistence.Iri sentenceIri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("delSentence", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                org.oor.persistence.IriHelper.write ($out, sentenceIri);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                delSentence (iri, sentenceIri        );
            } finally {
                _releaseReply ($in);
            }
  } // delSentence

  public void setMetricsList (org.oor.persistence.Iri iri, org.oor.persistence.Metrics[] metricsList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setMetricsList", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                org.oor.persistence.MetricsListHelper.write ($out, metricsList);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setMetricsList (iri, metricsList        );
            } finally {
                _releaseReply ($in);
            }
  } // setMetricsList

  public void addMetrics (org.oor.persistence.Iri iri, org.oor.persistence.Metrics metrics)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addMetrics", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                org.oor.persistence.MetricsHelper.write ($out, metrics);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addMetrics (iri, metrics        );
            } finally {
                _releaseReply ($in);
            }
  } // addMetrics

  public void delMetrics (org.oor.persistence.Iri iri, org.oor.persistence.Iri metricsIri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("delMetrics", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                org.oor.persistence.IriHelper.write ($out, metricsIri);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                delMetrics (iri, metricsIri        );
            } finally {
                _releaseReply ($in);
            }
  } // delMetrics

  public void setNoteList (org.oor.persistence.Iri iri, org.oor.persistence.Note[] noteList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setNoteList", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                org.oor.persistence.NoteListHelper.write ($out, noteList);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setNoteList (iri, noteList        );
            } finally {
                _releaseReply ($in);
            }
  } // setNoteList

  public void addNote (org.oor.persistence.Iri iri, org.oor.persistence.Note note)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addNote", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                org.oor.persistence.NoteHelper.write ($out, note);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addNote (iri, note        );
            } finally {
                _releaseReply ($in);
            }
  } // addNote

  public void delNote (org.oor.persistence.Iri iri, org.oor.persistence.Iri noteIri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("delNote", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                org.oor.persistence.IriHelper.write ($out, noteIri);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                delNote (iri, noteIri        );
            } finally {
                _releaseReply ($in);
            }
  } // delNote

  public void setMetadatumList (org.oor.persistence.Iri iri, org.oor.persistence.Metadatum[] metadatumList)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setMetadatumList", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                org.oor.persistence.MetadatumListHelper.write ($out, metadatumList);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setMetadatumList (iri, metadatumList        );
            } finally {
                _releaseReply ($in);
            }
  } // setMetadatumList

  public void addMetadatum (org.oor.persistence.Iri iri, org.oor.persistence.Metadatum metadatum)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addMetadatum", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                org.oor.persistence.MetadatumHelper.write ($out, metadatum);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addMetadatum (iri, metadatum        );
            } finally {
                _releaseReply ($in);
            }
  } // addMetadatum

  public void delMetadatum (org.oor.persistence.Iri iri, org.oor.persistence.Iri metadatumIri)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("delMetadatum", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                org.oor.persistence.IriHelper.write ($out, metadatumIri);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                delMetadatum (iri, metadatumIri        );
            } finally {
                _releaseReply ($in);
            }
  } // delMetadatum

  public void getContent (org.oor.persistence.Iri iri, org.oor.persistence.OntologyVersionContentHolder content)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getContent", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                $in = _invoke ($out);
                content.value = org.oor.persistence.OntologyVersionContentHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                getContent (iri, content        );
            } finally {
                _releaseReply ($in);
            }
  } // getContent

  public void setContent (org.oor.persistence.Iri iri, org.oor.persistence.OntologyVersionContent content)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("setContent", true);
                org.oor.persistence.IriHelper.write ($out, iri);
                org.oor.persistence.OntologyVersionContentHelper.write ($out, content);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                setContent (iri, content        );
            } finally {
                _releaseReply ($in);
            }
  } // setContent

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:org/oor/persistence/OntologyVersion:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _OntologyVersionStub
