package org.oor.persistence;


/**
* org/oor/persistence/BlobHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public final class BlobHolder implements org.omg.CORBA.portable.Streamable
{
  public char value[] = null;

  public BlobHolder ()
  {
  }

  public BlobHolder (char[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.oor.persistence.BlobHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.oor.persistence.BlobHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.oor.persistence.BlobHelper.type ();
  }

}
