package org.oor.persistence;


/**
* org/oor/persistence/LanguageHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

abstract public class LanguageHelper
{
  private static String  _id = "IDL:org/oor/persistence/Language:1.0";

  public static void insert (org.omg.CORBA.Any a, org.oor.persistence.Language that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.oor.persistence.Language extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.oor.persistence.IriHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "iri",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_alias_tc (org.oor.persistence.TextHelper.id (), "Text", _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "name",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.oor.persistence.LanguageHelper.id (), "Language", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.oor.persistence.Language read (org.omg.CORBA.portable.InputStream istream)
  {
    org.oor.persistence.Language value = new org.oor.persistence.Language ();
    value.iri = org.oor.persistence.IriHelper.read (istream);
    value.name = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.oor.persistence.Language value)
  {
    org.oor.persistence.IriHelper.write (ostream, value.iri);
    ostream.write_string (value.name);
  }

}
