package org.oor.persistence;


/**
* org/oor/persistence/LogicListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public final class LogicListHolder implements org.omg.CORBA.portable.Streamable
{
  public org.oor.persistence.Logic value[] = null;

  public LogicListHolder ()
  {
  }

  public LogicListHolder (org.oor.persistence.Logic[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.oor.persistence.LogicListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.oor.persistence.LogicListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.oor.persistence.LogicListHelper.type ();
  }

}
