package org.oor.persistence;


/**
* org/oor/persistence/Logic.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public final class Logic implements org.omg.CORBA.portable.IDLEntity
{
  public org.oor.persistence.Iri iri = null;
  public String name = null;

  public Logic ()
  {
  } // ctor

  public Logic (org.oor.persistence.Iri _iri, String _name)
  {
    iri = _iri;
    name = _name;
  } // ctor

} // class Logic
