package org.oor.persistence;


/**
* org/oor/persistence/Metadatum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public final class Metadatum implements org.omg.CORBA.portable.IDLEntity
{
  public org.oor.persistence.Iri iri = null;
  public org.oor.persistence.Iri kindIri = null;
  public org.oor.persistence.Iri kindName = null;
  public org.oor.persistence.Iri entryIri = null;
  public String value = null;

  public Metadatum ()
  {
  } // ctor

  public Metadatum (org.oor.persistence.Iri _iri, org.oor.persistence.Iri _kindIri, org.oor.persistence.Iri _kindName, org.oor.persistence.Iri _entryIri, String _value)
  {
    iri = _iri;
    kindIri = _kindIri;
    kindName = _kindName;
    entryIri = _entryIri;
    value = _value;
  } // ctor

} // class Metadatum
