package org.oor.persistence;

/**
* org/oor/persistence/MetadatumHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public final class MetadatumHolder implements org.omg.CORBA.portable.Streamable
{
  public org.oor.persistence.Metadatum value = null;

  public MetadatumHolder ()
  {
  }

  public MetadatumHolder (org.oor.persistence.Metadatum initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.oor.persistence.MetadatumHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.oor.persistence.MetadatumHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.oor.persistence.MetadatumHelper.type ();
  }

}
