package org.oor.persistence;


/**
* org/oor/persistence/MetadatumListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

abstract public class MetadatumListHelper
{
  private static String  _id = "IDL:org/oor/persistence/MetadatumList:1.0";

  public static void insert (org.omg.CORBA.Any a, org.oor.persistence.Metadatum[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.oor.persistence.Metadatum[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.oor.persistence.MetadatumHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (org.oor.persistence.MetadatumListHelper.id (), "MetadatumList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.oor.persistence.Metadatum[] read (org.omg.CORBA.portable.InputStream istream)
  {
    org.oor.persistence.Metadatum value[] = null;
    int _len0 = istream.read_long ();
    value = new org.oor.persistence.Metadatum[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = org.oor.persistence.MetadatumHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.oor.persistence.Metadatum[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      org.oor.persistence.MetadatumHelper.write (ostream, value[_i0]);
  }

}
