package org.oor.persistence;

/**
* org/oor/persistence/MetricsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public final class MetricsHolder implements org.omg.CORBA.portable.Streamable
{
  public org.oor.persistence.Metrics value = null;

  public MetricsHolder ()
  {
  }

  public MetricsHolder (org.oor.persistence.Metrics initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.oor.persistence.MetricsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.oor.persistence.MetricsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.oor.persistence.MetricsHelper.type ();
  }

}
