package org.oor.persistence;


/**
* org/oor/persistence/Metrics.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public final class Metrics implements org.omg.CORBA.portable.IDLEntity
{
  public org.oor.persistence.Iri iri = null;
  public String name = null;
  public String value = null;

  public Metrics ()
  {
  } // ctor

  public Metrics (org.oor.persistence.Iri _iri, String _name, String _value)
  {
    iri = _iri;
    name = _name;
    value = _value;
  } // ctor

} // class Metrics
