package org.oor.persistence;


/**
* org/oor/persistence/Note.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public final class Note implements org.omg.CORBA.portable.IDLEntity
{
  public org.oor.persistence.Iri iri = null;
  public org.oor.persistence.Iri authorIri = null;
  public String authorName = null;
  public org.oor.persistence.Iri entryIri = null;
  public String entryComment = null;

  public Note ()
  {
  } // ctor

  public Note (org.oor.persistence.Iri _iri, org.oor.persistence.Iri _authorIri, String _authorName, org.oor.persistence.Iri _entryIri, String _entryComment)
  {
    iri = _iri;
    authorIri = _authorIri;
    authorName = _authorName;
    entryIri = _entryIri;
    entryComment = _entryComment;
  } // ctor

} // class Note
