package org.oor.persistence;


/**
* org/oor/persistence/OntologyVersionContent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public final class OntologyVersionContent implements org.omg.CORBA.portable.IDLEntity
{
  public org.oor.persistence.Iri iri = null;
  public char blob[] = null;
  public org.oor.persistence.Symbol symbolList[] = null;
  public org.oor.persistence.Sentence sentenceList[] = null;
  public org.oor.persistence.Metrics metricsList[] = null;
  public org.oor.persistence.Note noteList[] = null;
  public org.oor.persistence.Metadatum metadatumList[] = null;

  public OntologyVersionContent ()
  {
  } // ctor

  public OntologyVersionContent (org.oor.persistence.Iri _iri, char[] _blob, org.oor.persistence.Symbol[] _symbolList, org.oor.persistence.Sentence[] _sentenceList, org.oor.persistence.Metrics[] _metricsList, org.oor.persistence.Note[] _noteList, org.oor.persistence.Metadatum[] _metadatumList)
  {
    iri = _iri;
    blob = _blob;
    symbolList = _symbolList;
    sentenceList = _sentenceList;
    metricsList = _metricsList;
    noteList = _noteList;
    metadatumList = _metadatumList;
  } // ctor

} // class OntologyVersionContent
