package org.oor.persistence;


/**
* org/oor/persistence/OntologyContent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public final class OntologyContent implements org.omg.CORBA.portable.IDLEntity
{
  public org.oor.persistence.OntologyFractum fractum = null;
  public org.oor.persistence.OntologyVersionContent currentVersion = null;

  public OntologyContent ()
  {
  } // ctor

  public OntologyContent (org.oor.persistence.OntologyFractum _fractum, org.oor.persistence.OntologyVersionContent _currentVersion)
  {
    fractum = _fractum;
    currentVersion = _currentVersion;
  } // ctor

} // class OntologyContent
