package org.oor.persistence;


/**
* org/oor/persistence/OntologyBaseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public interface OntologyBaseOperations 
{
  void selectOntologyIriList (String name, String category, String group, org.oor.persistence.Iri languageIri, org.oor.persistence.Iri projectIri, org.oor.persistence.IriListHolder iriList);
  void selectOntologyIriListByName (String name, org.oor.persistence.IriListHolder iriList);
  void selectOntologyIriListByCategory (String category, org.oor.persistence.IriListHolder iriList);
  void selectOntologyIriListByGroup (String group, org.oor.persistence.IriListHolder iriList);
  void selectOntologyIriListByLanguageIri (org.oor.persistence.Iri languageIri, org.oor.persistence.IriListHolder iriList);
  void selectOntologyIriListByProjectIri (org.oor.persistence.Iri projectIri, org.oor.persistence.IriListHolder iriList);
  void getOntologyIriList ();
  void selectOntologyFractumList (String name, String category, String group, org.oor.persistence.Iri languageIri, org.oor.persistence.Iri projectIri, org.oor.persistence.OntologyFractumListHolder fractumList);
  void selectOntologyFractumListByName (String name, org.oor.persistence.OntologyFractumListHolder fractumList);
  void selectOntologyFractumListByCategory (String category, org.oor.persistence.OntologyFractumListHolder fractumList);
  void selectOntologyFractumListByGroup (String group, org.oor.persistence.OntologyFractumListHolder fractumList);
  void selectOntologyFracutmListByLanguageIri (org.oor.persistence.Iri languageIri, org.oor.persistence.OntologyFractumListHolder fractumList);
  void selectOntologyFractumListByProjectIri (org.oor.persistence.Iri projectIri, org.oor.persistence.OntologyFractumListHolder fractumList);
  void getOntologyFractumList ();
  void selectOntologyContentList (String name, String category, String group, org.oor.persistence.Iri languageIri, org.oor.persistence.Iri projectIri, org.oor.persistence.OntologyContentListHolder contentList);
  void selectOntologyContentListByName (String name, org.oor.persistence.OntologyContentListHolder contentList);
  void selectOntologyContentListByCategory (String category, org.oor.persistence.OntologyContentListHolder contentList);
  void selectOntologyContentListByGroup (String group, org.oor.persistence.OntologyContentListHolder contentList);
  void selectOntologyContentListByLanguageIri (org.oor.persistence.Iri languageIri, org.oor.persistence.OntologyContentListHolder contentList);
  void selectOntologyContentListByProjectIri (org.oor.persistence.Iri projectIri, org.oor.persistence.OntologyContentListHolder contentList);
  void getOntologyContentList ();
  void insertOntology (org.oor.persistence.OntologyContent ontologyContent, org.oor.persistence.IriHolder iri);
  void updateOntology (org.oor.persistence.OntologyContent ontologyContent);
  void removeOntology (org.oor.persistence.Iri iri);
} // interface OntologyBaseOperations
