package org.oor.persistence;


/**
* org/oor/persistence/OntologyVersionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

abstract public class OntologyVersionHelper
{
  private static String  _id = "IDL:org/oor/persistence/OntologyVersion:1.0";

  public static void insert (org.omg.CORBA.Any a, org.oor.persistence.OntologyVersion that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.oor.persistence.OntologyVersion extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (org.oor.persistence.OntologyVersionHelper.id (), "OntologyVersion");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.oor.persistence.OntologyVersion read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_OntologyVersionStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.oor.persistence.OntologyVersion value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static org.oor.persistence.OntologyVersion narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.oor.persistence.OntologyVersion)
      return (org.oor.persistence.OntologyVersion)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.oor.persistence._OntologyVersionStub stub = new org.oor.persistence._OntologyVersionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static org.oor.persistence.OntologyVersion unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.oor.persistence.OntologyVersion)
      return (org.oor.persistence.OntologyVersion)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.oor.persistence._OntologyVersionStub stub = new org.oor.persistence._OntologyVersionStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
