package org.oor.persistence;


/**
* org/oor/persistence/OntologyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public interface OntologyOperations 
{
  String getName (org.oor.persistence.Iri iri);
  String getDescription (org.oor.persistence.Iri iri);
  String[] getCategories (org.oor.persistence.Iri iri);
  String[] getGroups (org.oor.persistence.Iri iri);
  String[] getPrefixes (org.oor.persistence.Iri iri);
  org.oor.persistence.Iri getCurrentVersionIri (org.oor.persistence.Iri iri);
  void setName (org.oor.persistence.Iri iri, String name);
  void setDescription (org.oor.persistence.Iri iri, String description);
  void setCategories (org.oor.persistence.Iri iri, String[] categories);
  void addCateogry (org.oor.persistence.Iri iri, String category);
  void delCategory (org.oor.persistence.Iri iri, String category);
  void setGroups (org.oor.persistence.Iri iri, String[] groups);
  void addGroup (org.oor.persistence.Iri iri, String group);
  void delGroup (org.oor.persistence.Iri iri, String group);
  void setPrefixes (org.oor.persistence.Iri iri, String[] prefixes);
  void addPrefix (org.oor.persistence.Iri iri, String prefix);
  void delPrefix (org.oor.persistence.Iri iri, String prefix);
  void setCurrentVersionIri (org.oor.persistence.Iri iri);
  void getFractum (org.oor.persistence.Iri iri, org.oor.persistence.OntologyFractumHolder fractum);
  void getContent (org.oor.persistence.Iri iri, org.oor.persistence.OntologyContentHolder content);
  void setFractum (org.oor.persistence.Iri iri, org.oor.persistence.OntologyFractum fractum);
  void setContent (org.oor.persistence.Iri iri, org.oor.persistence.OntologyContent content);
  void getVersionIriList (org.oor.persistence.Iri iri, org.oor.persistence.IriHolder versionIriList);
  void setVersionIriList (org.oor.persistence.Iri iri, org.oor.persistence.Iri versionIriList);
  void addVersionIri (org.oor.persistence.Iri iri, org.oor.persistence.Iri versionIri);
  void delVersionIri (org.oor.persistence.Iri iri, org.oor.persistence.Iri versionIri);
} // interface OntologyOperations
