package org.oor.persistence;


/**
* org/oor/persistence/OntologyVersionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public interface OntologyVersionOperations 
{
  void getBlob (org.oor.persistence.Iri iri);
  void getSymbolList (org.oor.persistence.Iri iri, org.oor.persistence.SymbolListHolder symbolList);
  void getSentenceList (org.oor.persistence.Iri iri, org.oor.persistence.SentenceListHolder sentenceList);
  void getMetricsList (org.oor.persistence.Iri iri, org.oor.persistence.MetricsListHolder metricsList);
  void getNoteList (org.oor.persistence.Iri iri, org.oor.persistence.NoteListHolder noteList);
  void getMetadatumList (org.oor.persistence.Iri iri, org.oor.persistence.MetadatumListHolder metadatumList);
  void setSymbolList (org.oor.persistence.Iri iri, org.oor.persistence.Symbol[] symbolList);
  void addSymbol (org.oor.persistence.Iri iri, org.oor.persistence.Symbol symbol);
  void delSymbol (org.oor.persistence.Iri iri, org.oor.persistence.Iri symbolIri);
  void setSentenceList (org.oor.persistence.Iri iri, org.oor.persistence.Sentence[] sentenceList);
  void addSentence (org.oor.persistence.Iri iri, org.oor.persistence.Sentence sentence);
  void delSentence (org.oor.persistence.Iri iri, org.oor.persistence.Iri sentenceIri);
  void setMetricsList (org.oor.persistence.Iri iri, org.oor.persistence.Metrics[] metricsList);
  void addMetrics (org.oor.persistence.Iri iri, org.oor.persistence.Metrics metrics);
  void delMetrics (org.oor.persistence.Iri iri, org.oor.persistence.Iri metricsIri);
  void setNoteList (org.oor.persistence.Iri iri, org.oor.persistence.Note[] noteList);
  void addNote (org.oor.persistence.Iri iri, org.oor.persistence.Note note);
  void delNote (org.oor.persistence.Iri iri, org.oor.persistence.Iri noteIri);
  void setMetadatumList (org.oor.persistence.Iri iri, org.oor.persistence.Metadatum[] metadatumList);
  void addMetadatum (org.oor.persistence.Iri iri, org.oor.persistence.Metadatum metadatum);
  void delMetadatum (org.oor.persistence.Iri iri, org.oor.persistence.Iri metadatumIri);
  void getContent (org.oor.persistence.Iri iri, org.oor.persistence.OntologyVersionContentHolder content);
  void setContent (org.oor.persistence.Iri iri, org.oor.persistence.OntologyVersionContent content);
} // interface OntologyVersionOperations
