package org.oor.persistence;


/**
* org/oor/persistence/RepositoryContent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public final class RepositoryContent implements org.omg.CORBA.portable.IDLEntity
{
  public org.oor.persistence.Iri iri = null;
  public String name = null;
  public org.oor.persistence.OntologyContent ontologyContentList[] = null;

  public RepositoryContent ()
  {
  } // ctor

  public RepositoryContent (org.oor.persistence.Iri _iri, String _name, org.oor.persistence.OntologyContent[] _ontologyContentList)
  {
    iri = _iri;
    name = _name;
    ontologyContentList = _ontologyContentList;
  } // ctor

} // class RepositoryContent
