package org.oor.persistence;


/**
* org/oor/persistence/RepositoryFractum.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public final class RepositoryFractum implements org.omg.CORBA.portable.IDLEntity
{
  public org.oor.persistence.Iri iri = null;
  public String name = null;
  public org.oor.persistence.OntologyFractum ontologyFractumList[] = null;

  public RepositoryFractum ()
  {
  } // ctor

  public RepositoryFractum (org.oor.persistence.Iri _iri, String _name, org.oor.persistence.OntologyFractum[] _ontologyFractumList)
  {
    iri = _iri;
    name = _name;
    ontologyFractumList = _ontologyFractumList;
  } // ctor

} // class RepositoryFractum
