package org.oor.persistence;


/**
* org/oor/persistence/RepositoryBaseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public interface RepositoryBaseOperations 
{
  void selectRepositoryIriList (String name, org.oor.persistence.IriListHolder iriList);
  void selectRepositoryFractumList (String name, org.oor.persistence.RepositoryFractumListHolder repositoryFractumList);
  void selectRepositoryContentList (String name, org.oor.persistence.RepositoryContentListHolder repositoryContentList);
  void insertRepository (org.oor.persistence.RepositoryContent repositoryContent, org.oor.persistence.IriHolder iri);
  void updateRepository (org.oor.persistence.RepositoryContent repositoryContent);
  void removeRepository (org.oor.persistence.Iri iri);
} // interface RepositoryBaseOperations
