package org.oor.persistence;


/**
* org/oor/persistence/RepositoryBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public interface RepositoryBase extends RepositoryBaseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RepositoryBase
