package org.oor.persistence;


/**
* org/oor/persistence/Sentence.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public final class Sentence implements org.omg.CORBA.portable.IDLEntity
{
  public org.oor.persistence.Iri iri = null;
  public String form = null;

  public Sentence ()
  {
  } // ctor

  public Sentence (org.oor.persistence.Iri _iri, String _form)
  {
    iri = _iri;
    form = _form;
  } // ctor

} // class Sentence
