package org.oor.persistence;

/**
* org/oor/persistence/SentenceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public final class SentenceHolder implements org.omg.CORBA.portable.Streamable
{
  public org.oor.persistence.Sentence value = null;

  public SentenceHolder ()
  {
  }

  public SentenceHolder (org.oor.persistence.Sentence initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.oor.persistence.SentenceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.oor.persistence.SentenceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.oor.persistence.SentenceHelper.type ();
  }

}
