package org.oor.persistence;


/**
* org/oor/persistence/Symbol.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from src/Ontology.idl
* Dienstag, 30. Juli 2013 15:56 Uhr MESZ
*/

public final class Symbol implements org.omg.CORBA.portable.IDLEntity
{
  public org.oor.persistence.Iri iri = null;
  public String kind = null;

  public Symbol ()
  {
  } // ctor

  public Symbol (org.oor.persistence.Iri _iri, String _kind)
  {
    iri = _iri;
    kind = _kind;
  } // ctor

} // class Symbol
